{{- if .Values.webui.enabled }}
{{- if .Values.webui.gatewayApi.enabled -}}
{{- $fullName := include "garage.fullname" . -}}
{{- $svcPort := .Values.webui.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-webui
  labels:
    {{- include "garage.webui.labels" . | nindent 4 }}
    {{- with .Values.webui.gatewayApi.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webui.gatewayApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.webui.gatewayApi.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.webui.gatewayApi.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.webui.gatewayApi.additionalRules }}
    {{- tpl (toYaml .Values.webui.gatewayApi.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ $fullName }}-webui
          port: {{ $svcPort }}
          weight: 100
      {{- with .Values.webui.gatewayApi.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.gatewayApi.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
{{- end }}
{{- end }}
